import type { Post } from "./post-types";

// SEO content set 3 — transcription how-tos, software comparisons and compliance.
export const SET_3: Post[] = [
  {
    slug: "how-to-record-and-transcribe-meetings",
    title: "How to Record and Transcribe Meetings Automatically",
    description: "You can record and transcribe meetings in three ways: built-in platform tools, cloud AI notetakers, or local tools. Here's how each option works and what to consider.",
    keyword: "record and transcribe meetings",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "Recording a meeting is now a one-click action in most video platforms. Transcribing it automatically is only slightly harder. But the choice of how you transcribe has significant privacy, compliance and accuracy implications." },
      { type: "h2", text: "Option 1: Built-in platform transcription" },
      { type: "p", text: "Zoom, Microsoft Teams and Google Meet all offer native transcription. Zoom's AI Companion and Teams Copilot produce transcripts and summaries during a live call. These are the easiest options, but they require a paid plan, process audio on the vendor's cloud, and generate consent/notification requirements under US two-party consent laws and GDPR." },
      { type: "h2", text: "Option 2: Cloud AI notetakers" },
      { type: "p", text: "Services like Otter.ai, Fireflies, Fathom and Read.ai join your meeting as a bot (or connect to your calendar) and produce a transcript and summary sent to your email. They are reliable and feature-rich, but they upload your meeting audio or transcript to a third-party server, which creates data security and compliance questions — especially for healthcare, legal and financial firms." },
      { type: "h2", text: "Option 3: Local on-device transcription" },
      { type: "p", text: "Tools like ParleyNotes run the transcription engine (typically OpenAI's Whisper model) directly in your browser or on your computer. Audio never leaves your device. This eliminates third-party data exposure entirely and does not require informing other participants that a recording bot is present — the tool processes audio locally in real time." },
      { type: "h2", text: "What to consider when choosing" },
      { type: "ul", items: [
        "Data sensitivity: Does your meeting content include PII, PHI, legal strategy or trade secrets?",
        "Consent requirements: Some states require all parties to consent to recording.",
        "Platform: Do you need live transcription, or can you transcribe a recording after the call?",
        "Cost: Built-in features are often included with paid plans; third-party bots add per-seat or per-hour costs.",
        "Privacy: On-device tools have zero data-sharing risk; cloud tools share audio with the vendor.",
      ] },
    ],
  },
  {
    slug: "offline-meeting-transcription",
    title: "Offline Meeting Transcription: No Cloud Required",
    description: "Offline transcription runs the AI model on your device, keeping audio local. Here's how browser-based Whisper works, who needs it, and how accurate it is.",
    keyword: "offline transcription",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Offline meeting transcription means the AI model runs on your computer or in your browser without sending audio to a server. It is now practical for most laptops thanks to WebAssembly, GPU acceleration and open-source model weights like OpenAI's Whisper." },
      { type: "h2", text: "How browser-based offline transcription works" },
      { type: "p", text: "Tools like ParleyNotes use WebAssembly to run Whisper directly in your browser tab. The first time, the model weights (50–150 MB depending on size) download to your device and are cached for future use. After that, transcription works completely offline — even with the network disconnected. Your audio is processed locally and never transmitted." },
      { type: "h2", text: "Who needs offline transcription" },
      { type: "ul", items: [
        "Healthcare teams: conversations about patients may constitute PHI under HIPAA — local processing avoids a covered business-associate relationship with a cloud vendor.",
        "Legal teams: attorney-client privilege concerns apply to any privileged communications transmitted to third parties.",
        "Finance and M&A: deal discussions and financial data have regulatory and confidentiality implications.",
        "Government contractors: some meetings may involve CUI (Controlled Unclassified Information) that cannot be processed on commercial cloud services.",
        "Anyone who has not obtained consent for cloud recording from all participants.",
      ] },
      { type: "h2", text: "Accuracy of offline Whisper transcription" },
      { type: "p", text: "Whisper large-v3 (the largest model) achieves word error rates of 2–5% on clear English speech — competitive with or better than most cloud services. Smaller models (whisper-tiny, whisper-base) are faster but less accurate. Browser-based implementations typically use the small or medium model to balance speed and accuracy on consumer hardware." },
    ],
  },
  {
    slug: "transcribe-zoom-recordings-guide",
    title: "How to Transcribe a Zoom Recording After the Call",
    description: "You can transcribe a Zoom recording using Zoom's built-in transcript, a local file transcription tool, or a third-party upload service. Here's how each method works.",
    keyword: "transcribe zoom recording",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "You recorded a Zoom call and now you need a transcript. Zoom offers a built-in option, but there are also third-party and local approaches that offer better privacy or more flexible output formats." },
      { type: "h2", text: "Method 1: Zoom's built-in transcript" },
      { type: "p", text: "Zoom Business and Pro plans with cloud recording enabled automatically generate a transcript (VTT or TXT format) when the recording is saved to Zoom's cloud. Find it in the Zoom web portal under Recordings. The transcript is also editable in the portal. Downside: it only works with cloud recordings; local MP4 files from local recordings do not get a transcript automatically. Zoom AI Companion (included with most paid Zoom plans) also provides summaries of cloud recordings." },
      { type: "h2", text: "Method 2: Upload the recording to a transcription service" },
      { type: "p", text: "If you have a local MP4 file, you can upload it to Otter.ai, Fireflies, AssemblyAI, or similar services for transcription. Upload, wait a few minutes, and download the transcript. This is fast and produces good results, but it sends the audio file to a third-party server — consider whether your meeting content is appropriate for that." },
      { type: "h2", text: "Method 3: Transcribe the recording locally" },
      { type: "p", text: "ParleyNotes and similar tools can transcribe a local video or audio file directly in your browser using the Whisper model. Drop the MP4 or M4A onto the tool and the audio is decoded and transcribed on-device, with no upload. This is ideal for sensitive recordings or where you want to avoid third-party data sharing. Speed depends on your GPU; a 1-hour recording typically transcribes in 5–15 minutes on a modern laptop." },
      { type: "h2", text: "Which format should you export?" },
      { type: "p", text: "Most tools offer SRT (for video subtitles), VTT (similar to SRT), TXT (plain text) and sometimes JSON. For meeting minutes, plain TXT is easiest to paste and edit. For sharing video with captions, SRT is the standard. If you need speaker identification (diarization), look for services that offer that specifically — basic Whisper transcription does not separate speakers." },
    ],
  },
  {
    slug: "automatic-notes-in-microsoft-teams",
    title: "Getting Automatic Meeting Notes in Microsoft Teams",
    description: "Microsoft Teams offers Copilot for live transcription and summaries on paid plans. Here's what each plan includes, what you can do without Copilot, and local alternatives.",
    keyword: "automatic meeting notes in teams",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Microsoft Teams has built-in tools for meeting notes, but the fully automatic AI version — the one that summarises the meeting, captures decisions and extracts action items — requires Microsoft 365 Copilot, which is a paid add-on." },
      { type: "h2", text: "What each tier gets you" },
      { type: "ul", items: [
        "Teams Essentials / Business Basic: manual meeting notes in the in-meeting Notes panel; no automatic transcription.",
        "Teams Business / Teams Essentials with Transcription: live captions and meeting transcripts (VTT/DOCX) available for recorded meetings.",
        "Microsoft 365 Copilot: AI-powered intelligent recap — automatic summary, speaker-separated transcript, action items, and follow-up suggestions. Requires Microsoft 365 E3/E5 + Copilot add-on.",
      ] },
      { type: "h2", text: "Using Teams Transcription without Copilot" },
      { type: "p", text: "If your plan includes transcription but not Copilot, you can enable live transcription during a meeting (More Actions → Start Transcription) and download the transcript after. The transcript is available in the meeting recording in OneDrive or SharePoint. It is raw — no AI summary — but serviceable for generating your own minutes." },
      { type: "h2", text: "Local alternatives for Teams meetings" },
      { type: "p", text: "If you do not have Copilot access, you can transcribe Teams recordings locally with a tool like ParleyNotes. Download the recording from OneDrive or SharePoint (MP4 format), then open it in ParleyNotes for on-device transcription and summarisation. The audio never leaves your device — no Copilot license needed." },
      { type: "h2", text: "Notification requirements" },
      { type: "p", text: "When you start a recording in Teams, all participants see a notification banner and can object. Meeting transcription in Teams also sends a notification. If participants are in a state with two-party consent laws (California, Illinois, etc.), participants' explicit consent is required before recording or transcribing." },
    ],
  },
  {
    slug: "meeting-recording-transcription-software-compared",
    title: "Meeting Recording and Transcription Software Compared",
    description: "Otter, Fireflies, Fathom, Read.ai and local tools like ParleyNotes all transcribe meetings differently. Here's a comparison across privacy, accuracy, price and features.",
    keyword: "meeting recording transcription software",
    date: "2026-06-20",
    readMins: 7,
    body: [
      { type: "p", text: "The meeting transcription market has exploded since 2022. There are now dozens of tools that join your calls, record, transcribe and summarise. Here's how the main categories compare." },
      { type: "h2", text: "Bot-based cloud notetakers" },
      { type: "p", text: "Otter.ai, Fireflies.ai, Fathom, Read.ai and Avoma all work by having a bot join your calendar-linked meeting. The bot records, transcribes in the cloud and sends you a summary. These are the most polished experience: the bot handles consent banners, speaker ID, action item extraction and integrations with Slack, Notion and CRMs. Downside: audio is on their servers. Pricing ranges from free (with limits) to $20–$40/user/month." },
      { type: "h2", text: "Platform-native transcription" },
      { type: "p", text: "Zoom, Teams, Meet and Webex have built-in transcription. It is tightly integrated with the platform and often included in paid plans. Quality is generally good; summaries require a premium AI add-on (Zoom AI Companion, Microsoft Copilot). It does not work across platforms — if you use multiple video tools, you need platform-specific features for each." },
      { type: "h2", text: "Local on-device transcription (ParleyNotes)" },
      { type: "p", text: "ParleyNotes runs Whisper in your browser. Audio never leaves your device. No bot joins your call — you transcribe live by sharing audio to the tool, or upload a recording file after. It works with any meeting platform. There is no speaker diarization in the basic version. Best for: sensitive meetings, compliance-heavy environments and users who do not want third-party data access." },
      { type: "h2", text: "Which should you choose?" },
      { type: "ul", items: [
        "Maximum convenience + don't care about data: Fathom (free tier is generous) or Otter.ai.",
        "Deeply integrated with Microsoft 365: Teams Copilot (expensive but native).",
        "Privacy-first, sensitive content, or no consent from attendees: ParleyNotes.",
        "Recording an uploaded file (post-call): ParleyNotes or AssemblyAI API.",
      ] },
    ],
  },
  {
    slug: "what-is-meeting-recording-software",
    title: "What Is Meeting Recording Software and Do You Need It?",
    description: "Meeting recording software captures audio, video and transcripts of calls. Here's how it differs from video conferencing built-ins and when it adds real value.",
    keyword: "meeting recording software",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Meeting recording software is a broad category covering any tool that captures a meeting, generates a transcript, produces a summary or stores the output for future reference. It includes built-in platform features, third-party bot-based tools and local on-device tools." },
      { type: "h2", text: "The problem it solves" },
      { type: "p", text: "Human note-taking during a meeting is imperfect. The note-taker misses content while writing, introduces their own framing and cannot document everything said. Recording the meeting and generating a verbatim transcript gives you an objective record. AI summarisation extracts the decisions, action items and key points automatically." },
      { type: "h2", text: "What it actually captures" },
      { type: "ul", items: [
        "Audio transcript: word-for-word text of who said what.",
        "Meeting summary: AI-generated overview of topics and decisions.",
        "Action items: tasks assigned during the meeting with owners and deadlines.",
        "Speaker identification: diarization labels each statement by speaker.",
        "Video recording: the visual record of screen shares and participant video.",
      ] },
      { type: "h2", text: "When you need dedicated software vs. platform features" },
      { type: "p", text: "Your video platform's built-in recording is sufficient if all your meetings happen on one platform and you only need the raw transcript. Third-party software adds cross-platform support, CRM integration, searchable transcript archives and team collaboration on notes. Local software adds zero-data-leakage privacy." },
      { type: "h2", text: "When you don't need it" },
      { type: "p", text: "For short internal calls where the output is a Slack message or two, meeting recording software is overkill. It shines for client calls, project kickoffs, interview recordings and any meeting where decisions and action items need a documented record." },
    ],
  },
  {
    slug: "transcribe-meeting-minutes-guide",
    title: "How to Transcribe Meeting Minutes Quickly and Accurately",
    description: "Transcribing meeting minutes from a recording is faster than writing from memory. Here's a workflow using AI transcription to produce clean, shareable meeting minutes.",
    keyword: "transcribe meeting minutes",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Typing up meeting minutes from memory or rough notes is tedious and inaccurate. A better workflow: record the meeting, transcribe the audio with AI, then edit and format the output into minutes. Here is how to do it quickly." },
      { type: "h2", text: "Step 1: Record the audio" },
      { type: "p", text: "Record the call using your video platform's built-in recording, or capture audio locally using system audio capture. For in-person meetings, a phone or a USB microphone running ParleyNotes captures room audio in real time. Get consent from participants where required." },
      { type: "h2", text: "Step 2: Transcribe with AI" },
      { type: "p", text: "Run the audio through an AI transcription tool. For a cloud recording, use the platform's built-in transcript or upload to Otter.ai or AssemblyAI. For sensitive meetings, use ParleyNotes to transcribe the file locally in your browser — the audio does not leave your device. A 60-minute meeting typically produces 8,000–12,000 words of transcript." },
      { type: "h2", text: "Step 3: Extract the key content" },
      { type: "p", text: "The raw transcript is verbose — every filler word, digression and side comment is included. Use AI summarisation (built into most tools) to pull out: attendees, decisions made, action items with owners and deadlines, topics discussed and deferred items. ParleyNotes generates a structured summary automatically after transcription." },
      { type: "h2", text: "Step 4: Format into minutes" },
      { type: "p", text: "Most organisations have a standard meeting minutes format. Copy the extracted items into your template: date, attendees, agenda, decisions, action items and next meeting date. A 60-minute meeting that used to take 30 minutes to write up can be done in 5–10 minutes with an AI-generated draft to edit." },
      { type: "h2", text: "Accuracy check" },
      { type: "p", text: "Always review AI-generated minutes before circulating. Whisper-based tools have 95–98% accuracy on clear audio, but proper nouns, technical terms and names are the most common errors. A quick read-through to fix names and numbers takes 2–3 minutes and prevents embarrassing errors in official minutes." },
    ],
  },
  {
    slug: "ai-meeting-summarizer-guide",
    title: "AI Meeting Summarizer: How It Works and What to Expect",
    description: "AI meeting summarizers produce a structured recap from a transcript. Here's how LLM-based summarization works, what it gets right, and where it still makes mistakes.",
    keyword: "meeting summarizer ai",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "An AI meeting summarizer takes a transcript and produces a structured overview: key topics, decisions made, action items and sometimes a verbatim quote or two. Most tools use a large language model (LLM) like GPT-4 or Claude for the summarisation step, after the audio has been transcribed with a speech-to-text model like Whisper." },
      { type: "h2", text: "The two-step pipeline" },
      { type: "p", text: "Meeting AI involves two separate AI systems: (1) a speech-to-text model converts audio to a word-for-word transcript, and (2) an LLM processes that transcript and extracts structure. Whisper handles the first step for most tools; the second step is where most products differentiate themselves, with custom prompts trained on meeting content." },
      { type: "h2", text: "What AI summaries get right" },
      { type: "p", text: "Modern AI meeting summaries are quite good at: extracting a bulleted list of topics discussed, identifying explicit decisions (when speakers say 'we decided', 'we will', 'agreed'), capturing action items when phrased directly ('John will send the report by Friday') and producing a readable paragraph summary of each section." },
      { type: "h2", text: "Where AI summaries still miss" },
      { type: "ul", items: [
        "Implicit decisions: things decided by consensus without an explicit statement.",
        "Tone and subtext: the AI cannot capture that a topic was contentious or that a stakeholder seemed unenthusiastic.",
        "Proper nouns and names: still the most common error; review these manually.",
        "Long meetings: summaries of 2+ hour meetings can lose fidelity on content from the middle section.",
        "Non-English speakers: accented English reduces transcription accuracy, which cascades to summary quality.",
      ] },
      { type: "h2", text: "Local vs cloud summarization" },
      { type: "p", text: "Cloud tools send your transcript to an LLM API for summarisation. ParleyNotes' summary step also uses an LLM, but can be configured to run locally using an open-source model on your device. This keeps both the audio and the summary generation off any external server — important for privileged or confidential meetings." },
    ],
  },
  {
    slug: "hipaa-compliant-meeting-notes",
    title: "HIPAA-Compliant Meeting Notes for Healthcare Teams",
    description: "Meeting notes that include patient information may be PHI under HIPAA. Here's what that means for recording, transcription and storage of clinical team meetings.",
    keyword: "hipaa compliant meeting recording",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "Healthcare organisations hold meetings that discuss patients — care coordination, case conferences, treatment team discussions. When those meetings are recorded or transcribed, the resulting files may contain Protected Health Information (PHI) and trigger HIPAA obligations." },
      { type: "h2", text: "When does HIPAA apply to meeting recordings?" },
      { type: "p", text: "HIPAA applies when: the meeting involves a covered entity (hospital, clinic, health plan, healthcare clearinghouse) or their business associates, and the recording or transcript contains PHI — information that identifies a patient in connection with their health, treatment or payment. A purely administrative meeting about billing software does not implicate HIPAA. A care conference discussing a specific patient's diagnosis and treatment plan does." },
      { type: "h2", text: "The business associate issue" },
      { type: "p", text: "If you send meeting audio or transcripts to a third-party service (an AI notetaker, a cloud transcription vendor), that vendor may become a business associate under HIPAA and require a Business Associate Agreement (BAA). Most general-purpose AI notetakers (Otter.ai, Fireflies, etc.) are not healthcare-specific and do not offer BAAs as a standard offering. Some have enterprise tiers with BAAs — check the vendor's current terms." },
      { type: "h2", text: "The local processing advantage" },
      { type: "p", text: "On-device transcription tools that process audio locally — like ParleyNotes — do not transmit audio to a third-party server. Because no data is shared with an external entity, the business-associate question does not arise. The transcript lives on your device and is subject to the same access controls as any other clinical document you create locally. This simplifies the HIPAA analysis significantly." },
      { type: "h2", text: "Storage and access controls" },
      { type: "p", text: "Regardless of how you transcribe, any meeting notes that contain PHI must be stored with appropriate access controls, retained per your organisation's policy, and disposed of securely when no longer needed. This applies to the transcript, the audio file, and any AI-generated summary." },
      { type: "p", text: "This post describes general HIPAA concepts. Consult your organisation's privacy officer and legal counsel for guidance on your specific workflows." },
    ],
  },
  {
    slug: "meeting-notes-for-remote-teams",
    title: "Meeting Notes for Remote Teams: Best Practices",
    description: "Remote teams depend on written meeting notes more than co-located ones. Here's how to structure notes, who owns them, and how to share them so everyone can act on them.",
    keyword: "meeting notes remote work",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "In a co-located office, decisions can be reinforced by walking over and asking. For remote and distributed teams, the written meeting note is the only reliable record. If it is not documented, it does not exist." },
      { type: "h2", text: "What remote meeting notes must include" },
      { type: "ul", items: [
        "Date, time and attendees (including who was absent).",
        "Agenda items and what was decided on each.",
        "Action items: specific task, who owns it, and a due date.",
        "Deferred items: topics that were raised but not resolved, and when they will be addressed.",
        "Context for those who were absent: enough background that a non-attendee can understand the decision without needing to ask.",
      ] },
      { type: "h2", text: "Who should take notes?" },
      { type: "p", text: "Rotating the note-taker role distributes the burden and prevents any one person from always being in 'support mode' during the meeting. If the meeting is being transcribed by AI, the designated note-taker's job shifts to reviewing and editing the AI output rather than writing from scratch — a much faster and lower-cognitive-load task." },
      { type: "h2", text: "Where to store and share notes" },
      { type: "p", text: "Notes should live somewhere the whole team can find them without asking: a shared Notion, Confluence, Google Doc or similar. Link the note to the recurring meeting in the calendar invite. Send a summary to the team Slack channel after each meeting with the key decisions and action items bolded — people skim Slack; full notes live in Notion." },
      { type: "h2", text: "AI transcription as a baseline" },
      { type: "p", text: "Using AI transcription and summarisation as a starting point dramatically reduces the effort of producing good meeting notes. The AI handles the verbatim transcript and pulls out explicit decisions and action items. The human note-taker reviews for accuracy, adds context the AI missed, and formats for readability. This typically takes 5–10 minutes after a 1-hour meeting." },
    ],
  },
  {
    slug: "how-to-choose-ai-meeting-recorder",
    title: "How to Choose the Best AI Meeting Recorder in 2026",
    description: "The best AI meeting recorder depends on your platform, privacy needs and budget. Here's a decision framework covering privacy, accuracy, integrations and cost.",
    keyword: "best ai meeting recorder",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "There is no single best AI meeting recorder — the right choice depends on your specific constraints. Here is a framework for making the decision." },
      { type: "h2", text: "Step 1: Assess your privacy requirements" },
      { type: "p", text: "Does your meeting content include PHI, legal privilege, financial data, or information about people who have not consented to cloud recording? If yes, you need either an on-device tool (ParleyNotes) or a cloud vendor with a specific BAA or data processing agreement for your use case. If no, any cloud tool is a reasonable option." },
      { type: "h2", text: "Step 2: Identify your platform" },
      { type: "p", text: "Bot-based tools work best when you use a single video platform consistently. If your meetings span Zoom, Teams, Google Meet, phone calls and in-person — a local tool or a bot that supports calendar integration across platforms gives you the most coverage. Platform-native tools (Teams Copilot, Zoom AI Companion) are only useful in their own platform." },
      { type: "h2", text: "Step 3: Decide what you need beyond transcription" },
      { type: "ul", items: [
        "Just transcription: ParleyNotes or any basic Whisper-based tool.",
        "Transcription + AI summary: most cloud bots or ParleyNotes with summarisation.",
        "CRM integration (auto-logging to Salesforce, HubSpot): Gong, Chorus, Fireflies.",
        "Speaker diarization (who said what): cloud services generally do this better than local tools.",
        "Searchable transcript library: cloud tools index and search; local tools save files to your machine.",
      ] },
      { type: "h2", text: "Step 4: Consider cost" },
      { type: "p", text: "Free tiers: Otter.ai free (600 min/month), Fathom free (unlimited with some limits), Fireflies free (limited transcripts). Paid cloud tiers: $15–$40/user/month. Local tools: often free or one-time purchase. For a 5-person team that has 20 hours of meetings per month, the math usually favors cloud tools unless privacy requires local." },
    ],
  },
  {
    slug: "getting-started-ai-meeting-notes",
    title: "Getting Started with AI for Meeting Notes",
    description: "Adding AI to your meeting workflow takes 10 minutes to set up and can save hours per week. Here's a beginner's guide from setup to your first AI-generated meeting summary.",
    keyword: "take meeting notes with ai",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "You don't need a technical background or a big budget to start using AI for meeting notes. Here's how to go from zero to your first AI-generated meeting summary in a few minutes." },
      { type: "h2", text: "Option A: Use a cloud notetaker (easiest)" },
      { type: "p", text: "Sign up for Otter.ai, Fathom or Fireflies. Connect it to your Google or Outlook calendar. When you join a meeting, the bot joins automatically and produces a transcript and summary afterwards, emailed to you within minutes of the call ending. This works without any setup during the meeting itself." },
      { type: "h2", text: "Option B: Use ParleyNotes (most private)" },
      { type: "p", text: "Open ParleyNotes in your browser. Click 'Start transcribing' and grant microphone access. The Whisper model loads in your browser (first-time ~30 seconds). Click start when your meeting begins. The transcript appears in real time. At the end, click 'Summarise' for an AI-generated recap. No account needed, no data uploaded." },
      { type: "h2", text: "What makes a good AI meeting note" },
      { type: "ul", items: [
        "State decisions explicitly during the meeting ('We have decided to...') so the AI can capture them.",
        "Name action-item owners directly ('Sarah will send the proposal by Tuesday').",
        "Avoid acronyms and internal jargon the AI won't know — or add a glossary to the prompt/template.",
        "Do a 2-minute review of the AI output before sending; fix proper nouns and names.",
      ] },
      { type: "h2", text: "Sharing the notes" },
      { type: "p", text: "Export to a Google Doc, paste into Notion or Confluence, or copy the action items into your project management tool. Most cloud notetakers have direct integrations with Notion, Asana and Slack. With ParleyNotes, copy and paste works fine — the output is clean Markdown that converts to any format." },
    ],
  },
];
