import type { Post } from "./post-types";

// SEO content set 2 — privacy, tech and "how to take notes" clusters.
export const SET_2: Post[] = [
  {
    slug: "private-on-device-meeting-transcription",
    title: "On-Device Meeting Transcription: Why It Matters",
    description: "What on-device (local) meeting transcription means, why it's more private than cloud notetakers, and how it changes your security review.",
    keyword: "private meeting notes",
    date: "2026-06-09",
    readMins: 5,
    body: [
      { type: "p", text: "On-device transcription means the speech-to-text model runs on your own computer instead of a remote server. For meeting notes — some of the most sensitive data a company handles — that distinction is everything." },
      { type: "h2", text: "Cloud vs on-device" },
      { type: "ul", items: ["Cloud: your audio is uploaded, transcribed remotely, and stored by the vendor", "On-device: your audio is transcribed locally and never leaves the machine"] },
      { type: "h2", text: "Why it changes your security review" },
      { type: "p", text: "If no data leaves the device, there's no third-party data-processing agreement to negotiate, no sub-processor list to vet, and no breach surface at the vendor. Tools that would otherwise be blocked sail through review." },
      { type: "h2", text: "Is it accurate enough?" },
      { type: "p", text: "Yes. Modern browsers can run OpenAI's Whisper via WebGPU at near-real-time speeds, and Whisper is the same family of model the cloud tools use. You get comparable accuracy without the upload." },
    ],
  },
  {
    slug: "whisper-in-the-browser-explained",
    title: "How Whisper Runs in Your Browser (No Server Needed)",
    description: "A plain-English explanation of how OpenAI's Whisper model runs entirely in the browser with WebGPU and WebAssembly — and why that's a big deal.",
    keyword: "open source transcription",
    date: "2026-06-08",
    readMins: 6,
    body: [
      { type: "p", text: "It used to be that speech-to-text required a server with a GPU. Now it can run in a browser tab. Here's how that became possible and what it unlocks." },
      { type: "h2", text: "The pieces" },
      { type: "ul", items: ["Whisper — OpenAI's open speech-recognition model, available in small, fast variants", "Transformers.js — runs Hugging Face models in JavaScript", "WebGPU / WebAssembly — let the browser do heavy maths efficiently"] },
      { type: "h2", text: "What happens when you record" },
      { type: "p", text: "The browser captures your audio, resamples it to 16 kHz, and feeds it to a Whisper model that was downloaded once from a CDN and cached. The model produces text — all on your device. No audio is ever uploaded." },
      { type: "h2", text: "Why it's a big deal" },
      { type: "p", text: "It removes the server from the privacy equation entirely, makes the tool free to run at scale, and works offline after the first model load. ParleyNotes is built on exactly this stack." },
    ],
  },
  {
    slug: "free-meeting-transcription-tools",
    title: "The Truth About 'Free' Meeting Transcription Tools",
    description: "Most 'free' meeting transcribers cap your minutes or monetise your data. Here's how to get genuinely free, unlimited transcription.",
    keyword: "free meeting transcription",
    date: "2026-06-08",
    readMins: 5,
    body: [
      { type: "p", text: "Search 'free meeting transcription' and you'll find a lot of tools that are free in name only — they cap you at a few hundred minutes a month, or the free tier exists to funnel your data into a paid upsell." },
      { type: "h2", text: "The usual catches" },
      { type: "ul", items: ["Monthly minute limits that run out fast", "Watermarked or truncated exports", "Your recordings used to improve the vendor's models", "A bot that needs access to your whole calendar"] },
      { type: "h2", text: "Genuinely free" },
      { type: "p", text: "Because ParleyNotes runs on your device, there's no server cost to recoup — so it's free for individuals with no minute caps and no data harvesting. The paid tiers are strictly for teams and companies that want collaboration, SSO and support." },
    ],
  },
  {
    slug: "self-hosted-meeting-notes-for-enterprise",
    title: "Self-Hosted Meeting Notes for Security-Conscious Teams",
    description: "Why enterprises are moving to self-hosted, open-source meeting notes — and what to look for in a deployable AI notetaker.",
    keyword: "self hosted meeting notes",
    date: "2026-06-07",
    readMins: 6,
    body: [
      { type: "p", text: "For regulated industries and security-conscious teams, sending meeting audio to a third-party SaaS is a non-starter. Self-hosted, open-source meeting notes are the answer." },
      { type: "h2", text: "What 'self-hosted' should mean" },
      { type: "ul", items: ["The app runs inside your network or on infrastructure you control", "Transcription happens on the user's device or your own hardware", "The source is open so security can audit it", "SSO/SAML and an audit log for compliance"] },
      { type: "h2", text: "The ParleyNotes model" },
      { type: "p", text: "The core app is MIT-licensed and self-hostable for free. A Company license adds a supported Docker/Helm bundle, SSO/SAML, SCIM provisioning, an admin console and an SLA — the pieces an enterprise needs but the open-source build doesn't require you to buy." },
      { type: "h2", text: "Why open source wins the review" },
      { type: "p", text: "Auditability plus on-device processing means there's nothing for an attacker to exfiltrate from a vendor and nothing opaque for your security team to object to." },
    ],
  },
  {
    slug: "how-to-write-meeting-minutes",
    title: "How to Write Meeting Minutes (With a Free Template)",
    description: "A simple, reusable structure for clear meeting minutes — plus how to generate them automatically from a transcript.",
    keyword: "ai meeting minutes",
    date: "2026-06-07",
    readMins: 5,
    body: [
      { type: "p", text: "Good minutes aren't a transcript — they're a short, scannable record of what was decided and who's doing what. Here's a structure that works for almost any meeting." },
      { type: "h2", text: "The template" },
      { type: "ul", items: ["Title, date and attendees", "Summary — 3 to 6 bullets of what was discussed", "Decisions — what was agreed", "Action items — owner, task and due date", "Open questions — what's still unresolved"] },
      { type: "h2", text: "Let AI do the first draft" },
      { type: "p", text: "Instead of writing minutes from memory, transcribe the meeting and generate the structure automatically. ParleyNotes produces exactly this layout from your transcript — summary, decisions, action items, open questions — which you then tidy in a minute or two." },
      { type: "h2", text: "Make action items stick" },
      { type: "p", text: "Always format actions as 'owner — task — due date'. Vague actions with no owner are the number one reason follow-ups slip." },
    ],
  },
  {
    slug: "extract-action-items-from-meetings",
    title: "How to Never Miss an Action Item From a Meeting",
    description: "Action items vanish because nobody captured them in the moment. Here's a system — and an automatic way — to extract them every time.",
    keyword: "ai meeting summary",
    date: "2026-06-06",
    readMins: 4,
    body: [
      { type: "p", text: "The most expensive part of a meeting isn't the hour — it's the commitments that get forgotten the moment it ends. A reliable action-item habit fixes that." },
      { type: "h2", text: "Capture cues in real time" },
      { type: "p", text: "Train yourself (and your tool) to flag phrases like 'I'll', 'we need to', 'let's', 'by Friday' and 'next step'. These almost always mark an action." },
      { type: "h2", text: "Automate it" },
      { type: "p", text: "ParleyNotes scans the transcript for exactly these cues and pulls out a clean action-item list — even without an AI key, using a local summarizer. Add your own AI key for a sharper, owner-attributed version." },
      { type: "h2", text: "Close the loop" },
      { type: "p", text: "Export the action items to your task tracker the same day. Notes that never leave the doc don't change behaviour." },
    ],
  },
  {
    slug: "meeting-notes-best-practices",
    title: "7 Meeting Notes Best Practices for 2026",
    description: "Practical, modern best practices for taking meeting notes that people actually read and act on.",
    keyword: "meeting notes app",
    date: "2026-06-06",
    readMins: 5,
    body: [
      { type: "p", text: "Most meeting notes are too long, too late, and never read. These seven practices keep them useful." },
      { type: "h2", text: "The practices" },
      { type: "ul", items: ["Decide the outcome you're capturing before the meeting starts", "Separate discussion from decisions from actions", "Attribute every action to one owner", "Keep the summary to six bullets or fewer", "Share within an hour, while it's fresh", "Store notes where people already look", "Protect sensitive notes — keep them on-device when you can"] },
      { type: "h2", text: "Let the tool carry the load" },
      { type: "p", text: "You can't follow these and also pay attention if you're typing furiously. Transcribe automatically and edit the generated structure — you get better notes and a better meeting." },
    ],
  },
  {
    slug: "ai-note-taker-privacy-guide",
    title: "Are AI Note Takers a Privacy Risk? A 2026 Guide",
    description: "What AI note takers actually do with your meeting data, the real privacy risks, and how to get the benefits without the exposure.",
    keyword: "ai notetaker",
    date: "2026-06-05",
    readMins: 6,
    body: [
      { type: "p", text: "AI note takers are genuinely useful — and a genuine privacy risk if you don't know where your audio goes. Here's what to check." },
      { type: "h2", text: "What most tools do with your data" },
      { type: "ul", items: ["Stream your meeting audio to their cloud via a bot", "Store transcripts and recordings on their servers", "Sometimes use your content to improve their models", "Require broad calendar and account permissions"] },
      { type: "h2", text: "The questions to ask" },
      { type: "ul", items: ["Where is my audio processed and stored?", "Is my content used for training?", "Can I delete everything, and is it really gone?", "Can I self-host or keep it on-device?"] },
      { type: "h2", text: "The low-risk option" },
      { type: "p", text: "On-device, open-source tools like ParleyNotes don't upload your audio at all, so most of these risks simply don't apply. You get the AI benefits — transcripts and structured notes — while your meetings stay yours." },
    ],
  },
];
