import type { Post } from "./post-types";

// SEO content set 1 — alternatives + platform how-tos. Targets validated
// keywords (live Google Ads, US, 2026-06-14).
export const SET_1: Post[] = [
  {
    slug: "open-source-granola-alternative",
    title: "The Best Open-Source Granola Alternative in 2026",
    description: "Granola is a great AI notepad, but it's closed-source, macOS-only and cloud-based. Here's the open-source, private, cross-platform alternative.",
    keyword: "open source granola",
    date: "2026-06-14",
    readMins: 6,
    body: [
      { type: "p", text: "Granola popularised the idea of an AI notepad that quietly listens to your meeting and turns your sparse notes into a polished summary. It's well-designed — but it's closed source, macOS-first, and it processes your meeting audio in its cloud. For a lot of people and most companies, that last point is a dealbreaker." },
      { type: "h2", text: "What an open-source Granola alternative should do" },
      { type: "ul", items: ["Transcribe meetings accurately, including the other participants — not just you", "Keep audio on your device so sensitive conversations never hit a third-party server", "Work on any OS, not just macOS", "Be free for individuals, with a clear, non-predatory upgrade path for teams", "Be genuinely open source so you can audit or self-host it"] },
      { type: "h2", text: "How ParleyNotes compares" },
      { type: "p", text: "ParleyNotes runs OpenAI's Whisper model directly in your browser using WebGPU or WebAssembly. The audio is captured from your meeting tab and microphone and transcribed locally — nothing is uploaded. It's MIT-licensed, so you can read the code, fork it, or run it inside your own network. And because the compute happens on your machine, it's free for individuals with no minute caps." },
      { type: "h2", text: "When Granola still makes sense" },
      { type: "p", text: "If you live entirely in macOS, want a native menu-bar app, and you're comfortable with cloud processing, Granola is polished and worth the subscription. If you care about privacy, cross-platform support, or open source — or you just don't want to pay per seat — ParleyNotes is the better fit." },
    ],
  },
  {
    slug: "best-ai-meeting-assistant-2026",
    title: "How to Choose an AI Meeting Assistant in 2026",
    description: "A practical guide to picking an AI meeting assistant — what features matter, the privacy trade-offs of bots and cloud transcription, and how to compare them.",
    keyword: "ai meeting assistant",
    date: "2026-06-13",
    readMins: 7,
    body: [
      { type: "p", text: "An AI meeting assistant records your calls, transcribes them and writes the notes so you can pay attention instead of typing. The category exploded over the last two years, and the tools now differ less on transcription quality than on how they handle your data." },
      { type: "h2", text: "The features that actually matter" },
      { type: "ul", items: ["Transcription accuracy on real, noisy calls — not just clean demo audio", "Whether a bot has to join the meeting (and show up in the participant list)", "Where audio is processed: your device, or the vendor's cloud", "How notes are structured: summary, decisions, action items", "Export and ownership — can you take your data with you?"] },
      { type: "h2", text: "The bot problem" },
      { type: "p", text: "Most assistants join your call as a participant bot. That's visible to everyone, it needs calendar access to do it automatically, and it means your audio streams to a third party. A browser-based assistant like ParleyNotes captures the meeting tab's audio directly, so there's no bot and no cloud upload." },
      { type: "h2", text: "Privacy is now the deciding factor" },
      { type: "p", text: "Meeting notes contain your most sensitive material: deals, hiring, strategy, 1:1s. Increasingly, security and legal teams won't approve a tool that ships all of that to an external cloud. On-device, open-source transcription sidesteps the entire review." },
      { type: "h2", text: "A simple shortlist test" },
      { type: "p", text: "Ask three questions: Does a bot join? Does my audio leave my device? Can I self-host if I need to? If the answers are no, no, and yes, you've found a tool your security team will actually approve." },
    ],
  },
  {
    slug: "otter-ai-alternatives",
    title: "5 Otter.ai Alternatives Worth Trying (Including a Private One)",
    description: "Otter.ai is popular but cloud-based with strict minute limits. Here are five alternatives, including a free, open-source, on-device option.",
    keyword: "otter ai alternatives",
    date: "2026-06-12",
    readMins: 6,
    body: [
      { type: "p", text: "Otter.ai is one of the best-known meeting transcribers, but two things send people looking for alternatives: the monthly transcription-minute caps on lower tiers, and the fact that every recording lives in Otter's cloud." },
      { type: "h2", text: "What to look for in an alternative" },
      { type: "ul", items: ["No (or generous) minute limits", "Clear data handling — ideally on-device", "Fair pricing for individuals", "Good export options"] },
      { type: "h2", text: "The alternatives" },
      { type: "ul", items: ["ParleyNotes — open source, transcribes in your browser, free for individuals, no minute caps", "Fireflies — bot-based, strong CRM integrations, cloud", "Fathom — generous free tier, bot-based, cloud", "tl;dv — great for clipping highlights, bot-based, cloud", "Notta — multi-language, freemium with limits, cloud"] },
      { type: "h2", text: "The private option" },
      { type: "p", text: "If your reason for leaving Otter is privacy or cost, the on-device approach wins outright: ParleyNotes never uploads your audio, has no minute caps, and is free for individuals. You only pay if you want a shared team workspace or a self-host bundle." },
    ],
  },
  {
    slug: "ai-meeting-notes-without-a-bot",
    title: "How to Get AI Meeting Notes Without a Bot Joining the Call",
    description: "Notetaker bots are awkward and a privacy risk. Here's how to capture AI meeting notes without any bot joining your Zoom, Meet or Teams call.",
    keyword: "ai meeting notes",
    date: "2026-06-12",
    readMins: 5,
    body: [
      { type: "p", text: "You've seen it: halfway through a call, 'Otter.ai Notetaker has joined the meeting' pops up and everyone pauses. Notetaker bots are intrusive, they need broad calendar permissions, and they stream your audio to a vendor's servers." },
      { type: "h2", text: "Why bots exist" },
      { type: "p", text: "Cloud notetakers can't hear your meeting unless something joins it. So they dispatch a bot to sit in the call and stream the audio out. It works, but it's visible and it's a privacy trade-off." },
      { type: "h2", text: "The bot-free approach" },
      { type: "p", text: "Browsers can already capture the audio of a tab you're in. ParleyNotes uses that: you share your meeting tab (with audio) and your microphone, and it transcribes the combined audio locally. No bot, nothing in the participant list, and no audio leaving your machine." },
      { type: "h2", text: "How to do it" },
      { type: "ul", items: ["Open your meeting in a browser tab (Zoom Web Client, Google Meet, Teams web)", "Open ParleyNotes and click Record", "Share the meeting tab and tick 'Share tab audio'", "Get a live transcript and one-click notes when you're done"] },
    ],
  },
  {
    slug: "how-to-transcribe-a-zoom-meeting",
    title: "How to Transcribe a Zoom Meeting for Free (Privately)",
    description: "A step-by-step guide to transcribing Zoom meetings for free, on your own device, without uploading anything to the cloud.",
    keyword: "zoom transcription",
    date: "2026-06-11",
    readMins: 5,
    body: [
      { type: "p", text: "Zoom's own transcription is fine, but it requires the right plan and it stores transcripts in Zoom's cloud. Here's how to transcribe any Zoom call for free and keep the transcript entirely on your device." },
      { type: "h2", text: "Step 1 — Run Zoom in the browser" },
      { type: "p", text: "Open the meeting with the Zoom Web Client (zoom.us/wc) so the call lives in a browser tab you can share." },
      { type: "h2", text: "Step 2 — Capture the tab audio" },
      { type: "ul", items: ["Open ParleyNotes and click 'Record meeting'", "When prompted, choose the Zoom tab and tick 'Share tab audio'", "Allow your microphone so your own voice is captured too"] },
      { type: "h2", text: "Step 3 — Get your notes" },
      { type: "p", text: "ParleyNotes transcribes the call in your browser as it happens. When you stop, click Generate notes for a summary, decisions and action items, then export Markdown. Nothing was uploaded to Zoom or anyone else." },
    ],
  },
  {
    slug: "how-to-transcribe-microsoft-teams-meetings",
    title: "How to Transcribe Microsoft Teams Meetings (No Teams Premium)",
    description: "Transcribe Microsoft Teams meetings for free without a Teams Premium licence — on-device, private, and exportable to Markdown.",
    keyword: "microsoft teams transcription",
    date: "2026-06-11",
    readMins: 5,
    body: [
      { type: "p", text: "Teams' built-in transcription is gated behind licensing and stores everything in Microsoft 365. If you want a free, private transcript — or your IT policy forbids external notetaker clouds — here's a clean way to do it." },
      { type: "h2", text: "Use the Teams web app" },
      { type: "p", text: "Join the meeting at teams.microsoft.com so it runs in a shareable browser tab." },
      { type: "h2", text: "Capture and transcribe" },
      { type: "ul", items: ["Open ParleyNotes and click Record", "Share the Teams tab and enable 'Share tab audio'", "Add your microphone so both sides are transcribed", "Everything is processed on your device — ideal for regulated industries"] },
      { type: "h2", text: "Why this works for compliance" },
      { type: "p", text: "Because the audio never leaves the browser, there's no data-processing agreement to negotiate and no external vendor touching meeting content. That's often the difference between a tool getting approved and getting blocked." },
    ],
  },
  {
    slug: "google-meet-transcription-guide",
    title: "Google Meet Transcription: A Free, Private Guide",
    description: "How to transcribe Google Meet calls for free without Workspace add-ons — on-device transcription and AI notes that stay private.",
    keyword: "google meet transcription",
    date: "2026-06-10",
    readMins: 4,
    body: [
      { type: "p", text: "Google Meet's transcription needs a paid Workspace tier and keeps transcripts in Google Drive. ParleyNotes gives you a free alternative that runs in the same browser tab and keeps everything local." },
      { type: "h2", text: "Steps" },
      { type: "ul", items: ["Join your Meet call (it already runs in the browser)", "Open ParleyNotes and click Record", "Share the Meet tab with 'Share tab audio' enabled", "Allow your mic so the whole conversation is captured"] },
      { type: "h2", text: "After the call" },
      { type: "p", text: "Generate notes with one click, edit the Markdown, and export or save it to your browser. Google never sees the transcript ParleyNotes builds." },
    ],
  },
  {
    slug: "fireflies-vs-otter-vs-parleynotes",
    title: "Fireflies vs Otter vs ParleyNotes: Which Meeting Notetaker?",
    description: "A clear comparison of Fireflies, Otter.ai and ParleyNotes across privacy, pricing, the bot question and open source.",
    keyword: "ai meeting notes",
    date: "2026-06-10",
    readMins: 6,
    body: [
      { type: "p", text: "Fireflies and Otter are two of the most popular AI notetakers. ParleyNotes takes a different architectural approach. Here's how they line up on the things that matter." },
      { type: "h2", text: "Bot vs no bot" },
      { type: "p", text: "Fireflies and Otter both rely on a bot joining your call (or a cloud recorder). ParleyNotes captures the meeting tab's audio directly in your browser — no bot in the participant list." },
      { type: "h2", text: "Where your audio goes" },
      { type: "p", text: "Fireflies and Otter process and store recordings in their cloud. ParleyNotes processes audio on your device and stores notes locally unless you export them." },
      { type: "h2", text: "Pricing" },
      { type: "ul", items: ["Fireflies — per-seat SaaS with a limited free tier", "Otter — freemium with monthly minute caps", "ParleyNotes — free for individuals with no minute caps; pay only for team/company features"] },
      { type: "h2", text: "Open source" },
      { type: "p", text: "Fireflies and Otter are closed source. ParleyNotes is MIT-licensed and self-hostable — the right pick if you need to audit the code or run it inside your own network." },
    ],
  },
];
